--liquibase formatted sql
--changeset EvgenyF:1

create table company
(
    id int4 generated by default as identity,
    active boolean, description varchar(255),
    name varchar(255),
    image_id int4,
    user_profile_id int4,
    primary key (id)
);
create table discount
(
    id int4 generated by default as identity,
    time time,
    value int2,
    primary key (id)
);
create table feedback
(
    id int4 generated by default as identity,
    text varchar(255),
    product_id int4,
    user_profile_id int4,
    primary key (id)
);
create table image
(
    id int4 generated by default as identity,
    data bytea,
    file_path varchar(255),
    file_size int8,
    media_type varchar(255),
    company_id int4, primary key (id)
);
create table notification
(
    id int4 generated by default as identity,
    date date,
    text varchar(255),
    user_profile_id int4,
    primary key (id)
);
create table product
(
    id int4 generated by default as identity,
    active boolean,
    description varchar(255),
    keywords varchar(255),
    price float4, quantity int4,
    title varchar(255),
    company_id int4,
    discount_id int4,
    primary key (id)
);
create table product_feature
(
    id int4 generated by default as identity,
    description varchar(255),
    title varchar(255),
    product_id int4,
    primary key (id)
);
create table purchase_history
(
    id int4 generated by default as identity,
    company varchar(255),
    company_description varchar(255),
    price float4, product varchar(255),
    product_description varchar(255),
    user_profile_id int4,
    primary key (id)
);
create table rating
(
    id int4 generated by default as identity,
    rating int2,
    product_id int4,
    user_profile_id int4,
    primary key (id)
);
create table user_profile
(
    id int4 generated by default as identity,
    balance float8,
    email varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);
alter table if exists company add constraint FKkhp2ql1t8e8qbps3gk3bp8pov foreign key (image_id) references image;
alter table if exists company add constraint FKeceyjrmdvrcu1oc8xeniwjbu7 foreign key (user_profile_id) references user_profile;
alter table if exists feedback add constraint FKlsfunb44jdljfmbx4un8s4waa foreign key (product_id) references product;
alter table if exists feedback add constraint FKnlbl90dwsb2yaj9oth8q1i84s foreign key (user_profile_id) references user_profile;
alter table if exists image add constraint FKpy9mcmnp51nntjpk10tekyxsp foreign key (company_id) references company;
alter table if exists notification add constraint FKfbwb0lp4nt69gqavtnaqlhxn foreign key (user_profile_id) references user_profile;
alter table if exists product add constraint FKghawd5rtv8ok565nwpdyyuto9 foreign key (company_id) references company;
alter table if exists product add constraint FKps2e0q9jpd0i9kj83je4rsmf1 foreign key (discount_id) references discount;
alter table if exists product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product;
alter table if exists purchase_history add constraint FKpyn9gvxbvyrdtf25nleiwpb0x foreign key (user_profile_id) references user_profile;
alter table if exists rating add constraint FKlkuwie0au2dru36asng9nywmh foreign key (product_id) references product;
alter table if exists rating add constraint FK6wgw8t7i4v371p558e0eqap5k foreign key (user_profile_id) references user_profile;
--liquibase formatted sql
--changeset EvgenyF:2
create table users
(
    username varchar(255),
    password varchar(255),
    enabled boolean,
    primary key (username)
);
alter table user_profile add  foreign key (username) references users;
create  table authorities
(username varchar(255),
 authority varchar(255),
 foreign key (username) references users
);
alter table discount add column  discount_period int4;
alter table discount add column date date;
alter table purchase_history add column date date;
alter table purchase_history alter column date type timestamp;

